name: Build

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - README.md
      - docs/**
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2
      - name: Run Build
        run: make build
        shell: bash
      - name: Run Test
        run: make test
        shell: bash
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
