name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - name: Run Test
        run: make test
        shell: bash
      - name: Build Release
        run: |
          export VERSION=${GITHUB_REF#refs/tags/}
          make release
        shell: bash
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/vmotion4bosh
